- name: Ansible Filters
  hosts: localhost
  tasks:
    - name: Print
      ansible.builtin.debug:
        msg: Yes we need to install
      when: install | bool

# ansible-playbook 10-filters.yml -e install=true
